### PR TITLE
Another attempt at lazy app initialization

### PR DESCRIPTION
**Pull request by andviro**
Hi! 

I hope this'll pass tests, it's very simple modification really.

Andrew

### CODE REVIEW

**Comment by DropD** [comment]
Is anything still preventing this from being pulled?

**Comment by wojcikstefan** [comment]
@andviro are you still using Flask-MongoRest? Would you mind handling the conflict so that we can give this another shot?

**Comment by andviro** [comment]
I'm sorry friends, it's been a long time, and I don't really remember what is what. I don't use Python in serious projects lately, switched to Golang in my work.

**Comment by wojcikstefan** [comment]
Ok, too bad this took so long. Good luck with your future projects @andviro !

I'm gonna close this PR and log the basic idea behind it as an issue (because it's still valid).

**Comment by frankV** [comment]
I'd like to take a crack at getting this merged in and carry the torch for @andviro 

Can someone catch me up? What was the conflict mentioned by @wojcikstefan on May 4th?

**Pull request closed without merging**
